#!/usr/bin/env bash
# install nginx and start the web server

apt-get -y update
apt-get -y install nginx
mkdir -p /var/www/html
echo "Hello World!" > /var/www/html/index.html
string="root /var/www/html;\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
sed -i "s,root /var/www/html;,$string," /etc/nginx/sites-available/default
service nginx restart
