#!/usr/bin/env bash
# install nginx and start the web server

apt-get -y update
apt-get -y install nginx
mkdir -p /var/www/html
echo "Ceci n'est pas une page" > /var/www/html/404.html
string="root /var/www/html;\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}\n"
sed -i "s,root /var/www/html;,$string," /etc/nginx/sites-available/default
service nginx restart
