#!/usr/bin/env bash
# debugging nginx
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw app list
sudo ufw allow 'Nginx HTTP'
sudo ufw status
sed -i 's/8080/80/' /etc/nginx/sites-enabled/default
sudo service nginx start
