#!/usr/bin/env bash
# This script display "Best School" 10 times with condition

counter=0
while (( counter < 10 ))
do
	echo "Best School"
	if (( counter == 8 ))
	then
		echo "Hi"
	fi
	((counter++))
done
