#!/usr/bin/env bash
# This script numbers from 1 to 20

number=1
while (( number < 21 ))
do
	echo "$number"
	case $number in
		4)
			echo "bad luck from China";;

		9)
			echo "bad luck from Japan";;
		17)
			echo "bad luck from Italy";;
	esac
	((number++))
done
