#!/usr/bin/env bash
# This script display the time for 12 hours and 59 minutes

hour=0
minute=1

while (( hour < 13 ))
do
	minute=1
	echo "Hour: $hour"
	while (( minute < 60 ))
	do
		echo "$minute"
		((minute++))
	done
	((hour++))
done
