#!/usr/bin/env bash
# This script show the content of the current directory only the part of the name after the first dash

for name in *
do
	if [ -e "$name" ]
	then
		echo "$name" | cut -d "-" -f 2
	fi
done
