#!/usr/bin/env bash
#run nginx as nginxuser

sudo chown -R nginx:nginx /var/log/nginx
sudo chown -R nginx:nginx /var/lib/nginx
user="user nginx;"
sed -i "1s/.*/$user/" /etc/nginx/nginx.conf
sed -i "s| 80 | 8080 |" /etc/nginx/sites-available/default
sed -i "s|:80 |:8080 |" /etc/nginx/sites-available/default
sudo systemctl restart nginx
